const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d');let items=[],selected=-1,drag=null;
const bg=document.getElementById('bgColor'),txt=document.getElementById('itemText'),tc=document.getElementById('textColor'),fs=document.getElementById('fontSize'),sc=document.getElementById('shapeColor');
function render(){ctx.fillStyle=bg.value;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#243957';ctx.lineWidth=1;for(let x=0;x<canvas.width;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,canvas.height);ctx.stroke()}for(let y=0;y<canvas.height;y+=45){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(canvas.width,y);ctx.stroke()}items.forEach((it,i)=>{ctx.save();if(it.type==='text'){ctx.font=`800 ${it.size}px Inter,Arial`;ctx.fillStyle=it.color;ctx.shadowColor=it.color;ctx.shadowBlur=12;ctx.fillText(it.text,it.x,it.y);}else if(it.type==='rect'){ctx.fillStyle=it.color;ctx.fillRect(it.x,it.y,it.w,it.h)}else{ctx.fillStyle=it.color;ctx.beginPath();ctx.arc(it.x,it.y,it.r,0,Math.PI*2);ctx.fill()}if(i===selected){ctx.shadowBlur=0;ctx.strokeStyle='#ffffff';ctx.setLineDash([6,4]);if(it.type==='text'){const w=ctx.measureText(it.text).width;ctx.strokeRect(it.x-5,it.y-it.size,w+10,it.size+10)}else if(it.type==='rect')ctx.strokeRect(it.x-4,it.y-4,it.w+8,it.h+8);else ctx.strokeRect(it.x-it.r-4,it.y-it.r-4,it.r*2+8,it.r*2+8)}ctx.restore()})}
function add(type){let obj;if(type==='text')obj={type,text:txt.value||'TEXT',color:tc.value,size:+fs.value,x:100+items.length*15,y:150+items.length*20};else if(type==='rect')obj={type,color:sc.value,x:130+items.length*10,y:180+items.length*10,w:220,h:115};else obj={type,color:sc.value,x:440,y:270,r:65};items.push(obj);selected=items.length-1;render()}
document.getElementById('addText').onclick=()=>add('text');document.getElementById('addRect').onclick=()=>add('rect');document.getElementById('addCircle').onclick=()=>add('circle');document.getElementById('clearCanvas').onclick=()=>{items=[];selected=-1;render()};
[bg,txt,tc,fs,sc].forEach(el=>el.addEventListener('input',()=>{if(selected>=0){let it=items[selected];if(it.type==='text'){it.text=txt.value;it.color=tc.value;it.size=+fs.value}else it.color=sc.value;}render()}));
function pos(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function hit(p,it){if(it.type==='rect')return p.x>=it.x&&p.x<=it.x+it.w&&p.y>=it.y&&p.y<=it.y+it.h;if(it.type==='circle')return Math.hypot(p.x-it.x,p.y-it.y)<=it.r;ctx.font=`800 ${it.size}px Inter,Arial`;return p.x>=it.x&&p.x<=it.x+ctx.measureText(it.text).width&&p.y>=it.y-it.size&&p.y<=it.y+8}
canvas.addEventListener('pointerdown',e=>{const p=pos(e);selected=-1;for(let i=items.length-1;i>=0;i--)if(hit(p,items[i])){selected=i;drag={p,it:items[i]};canvas.setPointerCapture(e.pointerId);break}render()});canvas.addEventListener('pointermove',e=>{if(!drag)return;const p=pos(e),dx=p.x-drag.p.x,dy=p.y-drag.p.y;const it=drag.it;if(it.type==='circle'){it.x+=dx;it.y+=dy}else{it.x+=dx;it.y+=dy}drag.p=p;render()});canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
document.getElementById('download').onclick=()=>{selected=-1;render();const a=document.createElement('a');a.download='designhub-artwork.png';a.href=canvas.toDataURL('image/png');a.click()};render();